#!/bin/bash

###########################################################################################
# Comments:
#
#------------------------------------------------------------------------------------------
# Author: John Albanese     
# Last Revision: 10/08/2016 
###########################################################################################

if [ $# -ne 2 ]
  then
    echo
    echo "Usage: ent_add_website <<Case Sensitive App Name>> <<Requester Id>>"
    echo
    exit
fi

dataDir="/enterprise_system/administration/data"
dataFile=$dataDir"/ent_app_driver.conf"
appName=$1
appReq=$2
searchAppName="\^"$appName"\^"

read activeDomain < $dataDir/active_domain

if [ `cat $dataFile|grep -c $searchAppName` -gt 0 ]
  then
      wget "https://console."$activeDomain".com/sendemail?subject=Enterprise Administrative Alert&msg=An attempt was made by developer "$appReq" to add a new website named "$appName". It was denied becuase the website already exists. See Splunk for details."
      rm ./sendemail* > /dev/null 2>&1
      exit
fi

rowToAdd="website^dev^"$appName"^https_http"
echo $rowToAdd >> $dataFile

read clientEmail < /enterprise_system/admin/data/guardian_email
wget "https://console."$activeDomain".com/sendemail?to=$clientEmail&subject=Enterprise Administrative Alert&msg=Developer "$appReq" added a new website named "$appName". Recycle DEV app services to activate modifications. See Splunk for details."
rm ./sendemail* > /dev/null 2>&1

exit


