#!/bin/bash

clear
if [ "$#" -ne 1 ]; then
    echo
    echo "Usage: go_conda <<New Anaconda Env without extension .yml>> OR <<Existing Anaconda Env with .yml extension>>)"
    echo
    exit
fi

if [ `echo $1|grep -c yml` -eq 0 ]
 then
    echo
    tput smso;echo -n " Verify: ";tput rmso;echo -n " Press Y to create new conda environment "$1" or any other key to exit... ";read pause
    echo
    if [ $pause == "Y" ]
      then
          conda create --name $1 python=3
    fi
    exit
fi

if [ ! -f /shared_anaconda_env/$1 ]
  then
     echo
     tput smso;echo -n "Error: ";tput rmso;echo " Anaconda .yml file "$1" does not exist in directory /shared_anaconda_env"
     echo
     exit
fi

conda env create -f /shared_anaconda_env/$1

exit

